let defaultConfig = require('tailwindcss/defaultConfig')

module.exports = {
  corePlugins: {
    container: false,
    appearance: false,
    backgroundAttachment: true,
    backgroundColor: true,
    backgroundPosition: true,
    backgroundRepeat: true,
    backgroundSize: true,
    borderColor: true,
    borderRadius: true,
    borderStyle: true,
    borderWidth: true,
    boxShadow: false,
    cursor: false,
    display: false,
    flex: false,
    flexDirection: false,
    flexGrow: false,
    flexShrink: false,
    fontSize: true,
    flexWrap: false,
    float: false,
    fontFamily: true,
    fontSmoothing: true,
    fontStyle: true,
    fontWeight: true,
    height: true,
    inset: false,
    justifyContent: false,
    letterSpacing: true,
    lineHeight: false,
    margin: true,
    maxHeight: false,
    maxWidth: false,
    minHeight: true,
    minWidth: true,
    negativeMargin: true,
    objectFit: false,
    objectPosition: false,
    opacity: true,
    outline: false,
    overflow: false,
    padding: true,
    pointerEvents: false,
    position: false,
    resize: true,
    stroke: false,
    tableLayout: false,
    textAlign: true,
    textColor: true,
    textDecoration: true,
    textTransform: true,
    userSelect: false,
    verticalAlign: true,
    visibility: true,
    whitespace: false,
    width: true,
    wordBreak: false,
    zIndex: true,
  },
  variants: {
    appearance: [],
    backgroundAttachment: [],
    backgroundColor: [],
    backgroundPosition: [],
    backgroundRepeat: [],
    backgroundSize: [],
    borderCollapse: [],
    borderColor: [],
    borderRadius: [],
    borderStyle: [],
    borderWidth: [],
    cursor: [],
    display: [],
    flexDirection: [],
    flexWrap: [],
    alignItems: [],
    alignSelf: [],
    justifyContent: [],
    alignContent: [],
    flex: [],
    flexGrow: [],
    flexShrink: [],
    order: [],
    float: [],
    fontFamily: [],
    fontWeight: [],
    height: [],
    lineHeight: [],
    listStylePosition: [],
    listStyleType: [],
    margin: [],
    maxHeight: [],
    maxWidth: [],
    minHeight: [],
    minWidth: [],
    negativeMargin: [],
    objectFit: [],
    objectPosition: [],
    opacity: [],
    outline: [],
    overflow: [],
    padding: [],
    pointerEvents: [],
    position: [],
    inset: [],
    resize: [],
    boxShadow: [],
    fill: [],
    stroke: [],
    tableLayout: [],
    textAlign: [],
    textColor: [],
    fontSize: [],
    fontStyle: [],
    textTransform: [],
    textDecoration: [],
    fontSmoothing: [],
    letterSpacing: [],
    userSelect: [],
    verticalAlign: [],
    visibility: [],
    whitespace: [],
    wordBreak: [],
    width: [],
    zIndex: [],
  },
  theme: {
    backgroundSize: {
      cover: 'cover',
      contain: 'contain',
    },
    borderRadius: {
      none: '0',
      sm: '2',
      default: '4',
      lg: '8',
      full: '9999',
    },
    borderWidth: {
      default: '1',
      px: '1px',
      '0': '0',
      '2': '2',
      '4': '4',
      '8': '8',
    },
    fontFamily: {
      'sans': [
        'system-ui',
        'BlinkMacSystemFont',
        '-apple-system',
        'Segoe UI',
        'Roboto',
        'Oxygen',
        'Ubuntu',
        'Cantarell',
        'Fira Sans',
        'Droid Sans',
        'Helvetica Neue',
        'sans-serif',
      ],
      'serif': [
        'Constantia',
        'Lucida Bright',
        'Lucidabright',
        'Lucida Serif',
        'Lucida',
        'DejaVu Serif',
        'Bitstream Vera Serif',
        'Liberation Serif',
        'Georgia',
        'serif',
      ],
      'mono': [
        'Menlo',
        'Monaco',
        'Consolas',
        'Liberation Mono',
        'Courier New',
        'monospace',
      ]
    },
    fontSize: {
      xs: '12',
      sm: '14',
      base: '16',
      lg: '18',
      xl: '20',
      '2xl': '24',
      '3xl': '30',
      '4xl': '36',
      '5xl': '48',
    },
    spacing: {
      px: '1px',
      '0': '0',
      '1': '4',
      '2': '8',
      '3': '12',
      '4': '16',
      '6': '24',
      '8': '32',
      '10': '40',
      '12': '48',
      '16': '64',
      '24': '96',
      '32': '128',
      '48': '192',
      '64': '1024',
    },
  },
}
